### ISSUE TITLE
Hardcoded namespace in KrateoPlatformOps resources

### ISSUE THREAD

**Issue by matteomasciari** [krateoplatformops/installer-chart#134]
**Describe the bug**
In both the templates:
- krateo-installer.yaml
- vcluster-installer.yaml

The namespace "krateo-system" is hardcoded, also in the different fields in the spec part.

This block the installation in a namespaces whit a different name

**To Reproduce**
helm repo add krateo https://charts.krateo.io
helm install installer krateo/installer --create-namespace -n <NAMESPACE_NAME> --wait

(where NAMESPACE_NAME is different from krateo-system)

**Expected behavior**
The installer pod came up, but nothing else happens

**Comment by braghettos** [comment]
@matteomasciari new release available: https://github.com/krateoplatformops/installer-chart/releases/tag/0.1.48
